### ISSUE TITLE
Improve environment command documentation

### ISSUE THREAD

**Issue by tharders** [jungvonmatt/contentful-migrations#17]
The "reset" option is not documented.
Also it is not documented how you can specify the source environment for a "create" environment call.

**Comment by tharders** [comment]
@bezoerb Is it currently possible to specify the source environment for a "create" or "reset" environment call?
If not we should really implement it.
If yes we should document it :-)

**Comment by bezoerb** [comment]
Hehe 😊
Thanks for the issue.
Always the same with those lousy documentations 😊
It should be possible using the `--source-environment-id` option. I'll see if I can document it later today.

**Comment by tharders** [comment]
Missing documentation now exists
