### ISSUE TITLE
Error: destEnvironment is not defined

### ISSUE THREAD

**Issue by DalkMania** [jungvonmatt/contentful-migrations#45]
Hi there I think I found a bug in your useful tool. 

https://github.com/jungvonmatt/contentful-migrations/blob/ba673e3c8b0a8a169dc0b7720606bb96de3a8c95/lib/content.js#L64

I think this is supposed to be destEnvironmentId ?

**Comment by bezoerb** [comment]
fixed in [v5.5.1](https://github.com/jungvonmatt/contentful-migrations/releases/tag/v5.5.1)

**Comment by bezoerb** [comment]
Thanks again @DalkMania 
If you find any other bugs feel free open more issues :D
