### ISSUE TITLE
Error occurs when running content command with diff flag

### ISSUE THREAD

**Issue by yvesgurcan** [jungvonmatt/contentful-migrations#48]
Running the command below:

```terminal
npx migrations content --verbose --diff --source-environment-id environment1 --dest-environment-id environment2
```

Results in this output:

```terminal
Fetching content from environment1 environment
Fetching content from environment2 environment

Error: assetOverwrites is not defined
```

It seems like the error is triggered from this line: https://github.com/jungvonmatt/contentful-migrations/blob/8e2b9180ed458ce6374df3f7c90ce2af850322e8/lib/content.js#L136

It looks like `assetOverwrites` might be a previously removed variable that is now undefined. The error only shows when using `--diff` due to the `if` statement that precedes the usage of this variable in the code.

Unfortunately, I'm not entirely sure if my assumption is correct as I'm not completely sure what the purpose of `assetOverwrites` was.

**Comment by bezoerb** [comment]
hey @yvesgurcan :)
thanks for opening this issue & the MR. I think you're absolutely right with your assumption. Looks like an outdated variable which has been removed along the way.

**Comment by bezoerb** [comment]
I manually manage the releases :)
[v5.5.2](https://github.com/jungvonmatt/contentful-migrations/releases/tag/v5.5.2)

**Comment by yvesgurcan** [comment]
Thank you! I'm able to run the diff now! :) I might have more issues and/or pull requests! :)
